version: '3.6'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=lordnr
      - POSTGRES_PASSWORD=lordnr1397
      - POSTGRES_DB=postgres

    ports:
      - "5432:5432"